### ISSUE TITLE
Ошибка ModuleNotFoundError: No module named 'aiogram.dispatcher.storage'

### ISSUE THREAD

**Issue by slv177** [DIMFLIX-OFFICIAL/AiogramStorages#3]
При попытке использования:

```
    sqlstorage = SQLiteStorage(db_path='bot.db')
    bot = Bot(token=config.tg_bot.token)
    dp = Dispatcher(storage=sqlstorage)
```

Получаю ошибку:
```
Traceback (most recent call last):
  File "/Users/SS/PycharmProjects/tgVrnRoutes/bot.py", line 10, in <module>
    from AiogramStorages.storages import SQLiteStorage
  File "/Users/SS/PycharmProjects/tgVrnRoutes/venv/lib/python3.11/site-packages/AiogramStorages/__init__.py", line 1, in <module>
    from . import storages
  File "/Users/SS/PycharmProjects/tgVrnRoutes/venv/lib/python3.11/site-packages/AiogramStorages/storages.py", line 6, in <module>
    from aiogram.dispatcher.storage import BaseStorage
ModuleNotFoundError: No module named 'aiogram.dispatcher.storage'
```

Python 3.11, aiogram==3.1.1.

**Comment by DIMFLIX** [comment]
Библиотека предназначена для 2-ой версии Aiogram.
В скором времени опубликую решение для 3-й версии. Следите за моим GitHub
